[package]
name = "hdl-sim"
version = "0.1.0"
edition = "2021"
build = "build.rs"

[dependencies]
riscv-sim = { path = "riscv-functional-sim/sim" }
riscv-codec = { git = "https://github.com/RebelAndroid/riscv-codec.git" }

[build-dependencies]
